version: '3.9'
services:
    database:
        image: mysql
        volumes:
            - mysql:/var/lib/mysql
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=core
            - MYSQL_DATABASE=core
            - MYSQL_USER=core
            - MYSQL_PASSWORD=core
        ports:
            - '3306:3306'
        networks:
            - intranet
networks:
    intranet:
volumes:
    mysql:
        name: mysqldb